version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: MySQL-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 1234Pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin-container
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
  app:
    container_name: Spring-Api-Container
    build: .
    depends_on:
      - db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/app_db
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRINGDOC_API-DOCS_PATH=/api-docs
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "8082:8082"
volumes:
  dbdata:
